// Realistic Checkpoints & Speed Enforcement Cameras Across Thailand (77 Provinces)
window.INITIAL_CHECKPOINTS = [
  {
    "id": "cp-bkk-01",
    "title": "ด่านตรวจวัดแอลกอฮอล์ ถ.รัชดาภิเษก",
    "type": "alcohol",
    "typeLabel": "ตรวจวัดแอลกอฮอล์",
    "locationName": "หน้า The Street รัชดา มุ่งหน้าแยกห้วยขวาง",
    "province": "กรุงเทพมหานคร",
    "district": "ดินแดง",
    "lat": 13.7709,
    "lng": 100.5735,
    "direction": "ขาออก (มุ่งหน้าแยกสุทธิสาร)",
    "status": "active",
    "verifiedCount": 58,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T10:45:00+07:00",
    "description": "เจ้าหน้าที่ สน.ห้วยขวาง มีเต็นท์ตรวจเป่าแอลกอฮอล์ บีบเหลือ 1 ช่องทางขวาสุด",
    "reportedBy": "สน.ห้วยขวาง & บก.จร.",
    "severity": "high"
  },
  {
    "id": "cp-bkk-02",
    "title": "จุดตรวจกวดขันวินัยจราจร สี่แยกอโศก-สุขุมวิท",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ใต้ BTS อโศก ถ.สุขุมวิท",
    "province": "กรุงเทพมหานคร",
    "district": "คลองเตย",
    "lat": 13.7372,
    "lng": 100.5604,
    "direction": "ขาเข้า (มุ่งหน้าเพลินจิต)",
    "status": "active",
    "verifiedCount": 34,
    "clearedCount": 4,
    "reportedAt": "2026-09-29T10:20:00+07:00",
    "description": "ตรวจหมวกกันน็อก ป้ายภาษี ใบขับขี่ รถจักรยานยนต์วิ่งเลนขวา",
    "reportedBy": "สน.ทองหล่อ",
    "severity": "medium"
  },
  {
    "id": "cp-bkk-03",
    "title": "กล้องตรวจจับความเร็วอัตโนมัติ ทางพิเศษศรีรัช (พระราม 9)",
    "type": "speed_camera",
    "typeLabel": "กล้องจับความเร็ว",
    "locationName": "ด่านศรีนครินทร์ มุ่งหน้าพระราม 9",
    "province": "กรุงเทพมหานคร",
    "district": "สวนหลวง",
    "lat": 13.7431,
    "lng": 100.612,
    "direction": "ขาเข้าเมือง",
    "status": "active",
    "verifiedCount": 112,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:00:00+07:00",
    "description": "กล้องเรดาร์ความเร็วอัตโนมัติ 24 ชม. จำกัดความเร็ว 110 กม./ชม.",
    "reportedBy": "การทางพิเศษแห่งประเทศไทย (กทพ.)",
    "severity": "high"
  },
  {
    "id": "cp-non-01",
    "title": "จุดตรวจกวดขันวินัยจราจรและแอลกอฮอล์ ถ.ราชพฤกษ์",
    "type": "alcohol",
    "typeLabel": "ตรวจแอลกอฮอล์ & จราจร",
    "locationName": "วงเวียนพระราม 5 ขาออก มุ่งหน้ารัตนาธิเบศร์",
    "province": "นนทบุรี",
    "district": "บางกรวย",
    "lat": 13.826,
    "lng": 100.449,
    "direction": "ขาออกเมือง",
    "status": "active",
    "verifiedCount": 41,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T11:15:00+07:00",
    "description": "เจ้าหน้าที่ สภ.บางกรวย ตั้งจุดตรวจวัดแอลกอฮอล์และตรวจสารเสพติด",
    "reportedBy": "สภ.บางกรวย",
    "severity": "high"
  },
  {
    "id": "cp-pte-01",
    "title": "ด่านตรวจตำรวจทางหลวงประตูน้ำพระอินทร์ ทล.1",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "พหลโยธิน กม.50 ขาออก มุ่งหน้าสระบุรี/อยุธยา",
    "province": "ปทุมธานี",
    "district": "คลองหลวง",
    "lat": 14.135,
    "lng": 100.615,
    "direction": "ขาออก (ทิศเหนือ)",
    "status": "active",
    "verifiedCount": 67,
    "clearedCount": 3,
    "reportedAt": "2026-09-29T09:30:00+07:00",
    "description": "ด่านถาวรตำรวจทางหลวง ตรวจรถบรรทุก รถกระบะบรรทุกสูง และวินัยจราจร",
    "reportedBy": "ตำรวจทางหลวง 1 กก.1",
    "severity": "medium"
  },
  {
    "id": "cp-pte-02",
    "title": "กล้องตรวจจับความเร็ว ถ.กาญจนาภิเษก ทล.9 (วงแหวนตะวันออก)",
    "type": "speed_camera",
    "typeLabel": "กล้องจับความเร็ว",
    "locationName": "กม.12 ช่วงคลองหลวง-บางปะอิน",
    "province": "ปทุมธานี",
    "district": "คลองหลวง",
    "lat": 14.072,
    "lng": 100.718,
    "direction": "ขาออก มุ่งหน้าสระบุรี",
    "status": "active",
    "verifiedCount": 95,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T07:30:00+07:00",
    "description": "กล้องเรดาร์จับความเร็วเลนขวาสุด เกิน 120 กม./ชม. มีใบสั่งส่งถึงบ้าน",
    "reportedBy": "กองบังคับการตำรวจทางหลวง",
    "severity": "high"
  },
  {
    "id": "cp-spk-01",
    "title": "กล้องตรวจจับความเร็ว ทางพิเศษบูรพาวิถี (กม.14)",
    "type": "speed_camera",
    "typeLabel": "กล้องจับความเร็ว",
    "locationName": "บูรพาวิถี กม.14 เหนือ ถ.บางนา-ตราด อ.บางพลี",
    "province": "สมุทรปราการ",
    "district": "บางพลี",
    "lat": 13.628,
    "lng": 100.725,
    "direction": "ขาออก มุ่งหน้าชลบุรี",
    "status": "active",
    "verifiedCount": 88,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:15:00+07:00",
    "description": "ตรวจจับความเร็วบนทางยกระดับ จำกัดความเร็ว 110 กม./ชม.",
    "reportedBy": "ตำรวจทางด่วนบูรพาวิถี",
    "severity": "high"
  },
  {
    "id": "cp-aya-01",
    "title": "สถานีตรวจสอบน้ำหนักยานพาหนะบางปะอิน ทล.32 (สายเอเชีย)",
    "type": "weight",
    "typeLabel": "ด่านชั่งน้ำหนัก & ตรวจวินัยจราจร",
    "locationName": "ทล.32 สายเอเชีย กม.4 ขาออก อ.บางปะอิน",
    "province": "พระนครศรีอยุธยา",
    "district": "บางปะอิน",
    "lat": 14.285,
    "lng": 100.598,
    "direction": "ขาออก (มุ่งหน้านครสวรรค์)",
    "status": "active",
    "verifiedCount": 73,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T09:00:00+07:00",
    "description": "สถานีชั่งน้ำหนักยานพาหนะถาวร กรมทางหลวง ร่วมกับตำรวจทางหลวง ตรวจรถบรรทุกและควันดำ",
    "reportedBy": "สำนักงานควบคุมน้ำหนักยานพาหนะ กรมทางหลวง",
    "severity": "high"
  },
  {
    "id": "cp-aya-02",
    "title": "จุดตรวจตำรวจทางหลวงวังน้อย ทล.1 พหลโยธิน",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "พหลโยธิน กม.64 อ.วังน้อย",
    "province": "พระนครศรีอยุธยา",
    "district": "วังน้อย",
    "lat": 14.241,
    "lng": 100.728,
    "direction": "ขาเข้า กทม.",
    "status": "active",
    "verifiedCount": 52,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:10:00+07:00",
    "description": "ตรวจรถตู้โดยสารสาธารณะ รถบัส และตรวจใบขับขี่ แอลกอฮอล์",
    "reportedBy": "ส.ทล.1 กก.1 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-ang-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.32 สายเอเชีย กม.52 แยกไชโย",
    "type": "speed_camera",
    "typeLabel": "ตรวจจับความเร็ว & จราจร",
    "locationName": "ทล.32 กม.52 แยกไชโย อ.ไชโย",
    "province": "อ่างทอง",
    "district": "ไชโย",
    "lat": 14.652,
    "lng": 100.485,
    "direction": "ขาขึ้นเหนือ (มุ่งหน้าสิงห์บุรี)",
    "status": "active",
    "verifiedCount": 44,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:40:00+07:00",
    "description": "กล้องเลเซอร์ตรวจจับความเร็วเคลื่อนที่ จำกัด 120 กม./ชม. บนสายเอเชีย",
    "reportedBy": "สภ.ไชโย",
    "severity": "high"
  },
  {
    "id": "cp-lob-01",
    "title": "จุดตรวจตำรวจทางหลวงโคกกะเทียม ทล.1 พหลโยธิน กม.158",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.1 พหลโยธิน กม.158 หน้า รพ.อานันทมหิดล",
    "province": "ลพบุรี",
    "district": "เมืองลพบุรี",
    "lat": 14.852,
    "lng": 100.672,
    "direction": "ขาเข้าเมืองลพบุรี",
    "status": "active",
    "verifiedCount": 38,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T10:30:00+07:00",
    "description": "จุดตรวจกวดขันวินัยจราจร ตรวจป้ายภาษี หมวกกันน็อก และตรวจหาสารเสพติด",
    "reportedBy": "สภ.เมืองลพบุรี",
    "severity": "medium"
  },
  {
    "id": "cp-sbr-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.32 สายเอเชีย กม.84 ต่างระดับสิงห์บุรีใต้",
    "type": "speed_camera",
    "typeLabel": "ตรวจจับความเร็ว",
    "locationName": "ทล.32 สายเอเชีย กม.84 ต่างระดับสิงห์บุรีใต้",
    "province": "สิงห์บุรี",
    "district": "เมืองสิงห์บุรี",
    "lat": 14.885,
    "lng": 100.412,
    "direction": "ขาล่องเข้า กทม.",
    "status": "active",
    "verifiedCount": 61,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:50:00+07:00",
    "description": "กล้องตรวจจับความเร็วสายเอเชีย ตรวจสอบรถวิ่งแช่ขวาและใช้ความเร็วเกินกำหนด",
    "reportedBy": "ตำรวจทางหลวงสิงห์บุรี",
    "severity": "high"
  },
  {
    "id": "cp-cnb-01",
    "title": "จุดตรวจตำรวจทางหลวงสรรพยา ทล.32 สายเอเชีย กม.118",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.32 สายเอเชีย กม.118 อ.สรรพยา",
    "province": "ชัยนาท",
    "district": "สรรพยา",
    "lat": 15.148,
    "lng": 100.225,
    "direction": "ขาขึ้นเหนือ (มุ่งหน้านครสวรรค์)",
    "status": "active",
    "verifiedCount": 49,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:15:00+07:00",
    "description": "จุดบริการและตรวจความพร้อมของผู้ขับขี่ ป้องกันหลับในและอุบัติเหตุ",
    "reportedBy": "ส.ทล.6 กก.1 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-sar-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ถ.มิตรภาพ ทล.2 กม.15 แก่งคอย",
    "type": "speed_camera",
    "typeLabel": "ตรวจจับความเร็ว & วินัยจราจร",
    "locationName": "ถ.มิตรภาพ กม.15 อ.แก่งคอย",
    "province": "สระบุรี",
    "district": "แก่งคอย",
    "lat": 14.585,
    "lng": 101.012,
    "direction": "ขาออก (มุ่งหน้าโคราช)",
    "status": "active",
    "verifiedCount": 77,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T10:00:00+07:00",
    "description": "กล้องจับความเร็วและตรวจจับรถบรรทุกวิ่งช่องทางขวาบน ถ.มิตรภาพ",
    "reportedBy": "ตำรวจทางหลวงสระบุรี",
    "severity": "high"
  },
  {
    "id": "cp-nyk-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.305 (รังสิต-นครนายก กม.68)",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.305 รังสิต-นครนายก กม.68 หน้าศาลากลางนครนายก",
    "province": "นครนายก",
    "district": "เมืองนครนายก",
    "lat": 14.205,
    "lng": 101.205,
    "direction": "ขาเข้าเมือง",
    "status": "active",
    "verifiedCount": 29,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:40:00+07:00",
    "description": "ตรวจหมวกกันน็อก ใบขับขี่ และเข็มขัดนิรภัย",
    "reportedBy": "สภ.เมืองนครนายก",
    "severity": "low"
  },
  {
    "id": "cp-npt-01",
    "title": "จุดตรวจตำรวจทางหลวงนครชัยศรี ทล.4 เพชรเกษม กม.42",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.4 เพชรเกษม กม.42 อ.นครชัยศรี",
    "province": "นครปฐม",
    "district": "นครชัยศรี",
    "lat": 13.785,
    "lng": 100.185,
    "direction": "ขาออก (มุ่งหน้าราชบุรี)",
    "status": "active",
    "verifiedCount": 55,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:20:00+07:00",
    "description": "ตรวจจับความเร็ว ตรวจรถบรรทุก และกวดขันวินัยจราจร",
    "reportedBy": "ส.ทล.1 กก.2 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-skn-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ถ.พระราม 2 ทล.35 กม.28",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร & ควันดำ",
    "locationName": "ทล.35 พระราม 2 กม.28 สะพานข้ามแม่น้ำท่าจีน",
    "province": "สมุทรสาคร",
    "district": "เมืองสมุทรสาคร",
    "lat": 13.542,
    "lng": 100.268,
    "direction": "ขาออก (มุ่งหน้าสมุทรสงคราม)",
    "status": "active",
    "verifiedCount": 48,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T09:50:00+07:00",
    "description": "ตรวจควันดำรถบรรทุกและรถกระบะ ตรวจการปฏิบัติตามกฎจราจรในเขตก่อสร้างทางยกระดับ",
    "reportedBy": "สภ.เมืองสมุทรสาคร",
    "severity": "medium"
  },
  {
    "id": "cp-skm-01",
    "title": "จุดตรวจตำรวจทางหลวงสมุทรสงคราม ทล.35 กม.63",
    "type": "speed_camera",
    "typeLabel": "กล้องจับความเร็ว & ตรวจจราจร",
    "locationName": "ทล.35 พระราม 2 กม.63 ต.บางขันแตก",
    "province": "สมุทรสงคราม",
    "district": "เมืองสมุทรสงคราม",
    "lat": 13.398,
    "lng": 99.982,
    "direction": "ขาออก (มุ่งหน้าแยกวังมะนาว)",
    "status": "active",
    "verifiedCount": 64,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T08:40:00+07:00",
    "description": "กล้องตรวจจับความเร็ว ถ.พระราม 2 ป้องกันอุบัติเหตุก่อนเข้าเขตเพชรบุรี",
    "reportedBy": "ตำรวจทางหลวงสมุทรสงคราม",
    "severity": "high"
  },
  {
    "id": "cp-spb-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.340 (บางบัวทอง-สุพรรณบุรี กม.65)",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.340 กม.65 อ.บางปลาม้า",
    "province": "สุพรรณบุรี",
    "district": "บางปลาม้า",
    "lat": 14.412,
    "lng": 100.145,
    "direction": "ขาเข้าเมืองสุพรรณบุรี",
    "status": "active",
    "verifiedCount": 35,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:15:00+07:00",
    "description": "กวดขันความเร็ว หมวกกันน็อก และเข็มขัดนิรภัยบนทางหลวงสายหลัก",
    "reportedBy": "สภ.บางปลาม้า",
    "severity": "medium"
  },
  {
    "id": "cp-cmi-01",
    "title": "ด่านตรวจถาวรแม่นะ ทล.107 (เชียงใหม่-ฝาง)",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.107 กม.68 ต.แม่นะ อ.เชียงดาว",
    "province": "เชียงใหม่",
    "district": "เชียงดาว",
    "lat": 19.342,
    "lng": 98.961,
    "direction": "ขาล่องเข้าตัวเมืองเชียงใหม่",
    "status": "active",
    "verifiedCount": 92,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T10:00:00+07:00",
    "description": "ด่านตรวจร่วมตำรวจ ทหาร ฝ่ายปกครอง ตรวจค้นยานพาหนะ สกัดกั้นยาเสพติดและสิ่งผิดกฎหมาย",
    "reportedBy": "สภ.เชียงดาว & ฉก.ม.4",
    "severity": "high"
  },
  {
    "id": "cp-cmi-02",
    "title": "จุดตรวจบูรณาการ สภ.สารภี ทล.11 (ซุปเปอร์ไฮเวย์)",
    "type": "speed_camera",
    "typeLabel": "ตรวจจับความเร็ว & แอลกอฮอล์",
    "locationName": "ทล.11 กม.548 ต.ยางเนิ้ง อ.สารภี",
    "province": "เชียงใหม่",
    "district": "สารภี",
    "lat": 18.725,
    "lng": 99.035,
    "direction": "ขาเข้าเชียงใหม่",
    "status": "active",
    "verifiedCount": 81,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T11:20:00+07:00",
    "description": "กล้องจับความเร็วอัตโนมัติบนซุปเปอร์ไฮเวย์ จำกัด 90 กม./ชม. และจุดตรวจเป่าแอลกอฮอล์กลางคืน",
    "reportedBy": "สภ.สารภี & กลุ่มงานจราจร ภ.จว.เชียงใหม่",
    "severity": "high"
  },
  {
    "id": "cp-cri-01",
    "title": "ด่านตรวจถาวรปูแกง ทล.1 พหลโยธิน กม.910",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.1 พหลโยธิน กม.910 ต.แม่เย็น อ.พาน",
    "province": "เชียงราย",
    "district": "พาน",
    "lat": 19.552,
    "lng": 99.745,
    "direction": "ขาล่องลง กทม.",
    "status": "active",
    "verifiedCount": 105,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:00:00+07:00",
    "description": "ด่านตรวจสกัดยาเสพติดหลักระดับประเทศ รอยต่อเชียงราย-พะเยา มีระบบเอ็กซเรย์ยานพาหนะและสุนัข K-9",
    "reportedBy": "สภ.พาน & บช.ปส.",
    "severity": "high"
  },
  {
    "id": "cp-lpn-01",
    "title": "จุดตรวจตำรวจทางหลวงดอยติ ทล.11 กม.528",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.11 แยกดอยติ อ.เมืองลำพูน",
    "province": "ลำพูน",
    "district": "เมืองลำพูน",
    "lat": 18.558,
    "lng": 99.042,
    "direction": "ขาขึ้นเชียงใหม่",
    "status": "active",
    "verifiedCount": 46,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:10:00+07:00",
    "description": "ตรวจความพร้อมรถโดยสาร ตรวจสารเสพติดคนขับ และกวดขันวินัยจราจร",
    "reportedBy": "ส.ทล.2 กก.5 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-lpg-01",
    "title": "ด่านตรวจถาวรสบปราบ ทล.1 พหลโยธิน กม.653",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.1 พหลโยธิน กม.653 ต.สบปราบ อ.สบปราบ",
    "province": "ลำปาง",
    "district": "สบปราบ",
    "lat": 17.882,
    "lng": 99.345,
    "direction": "ขาล่องเข้า กทม.",
    "status": "active",
    "verifiedCount": 128,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:30:00+07:00",
    "description": "ด่านตรวจถาวร สภ.สบปราบ สกัดกั้นยาเสพติดภาคเหนือ ตรวจเข้มรถยนต์และรถบรรทุก 24 ชั่วโมง",
    "reportedBy": "สภ.สบปราบ ภ.จว.ลำปาง",
    "severity": "high"
  },
  {
    "id": "cp-lpg-02",
    "title": "ด่านตรวจถาวรแม่พริก ทล.1 พหลโยธิน กม.595",
    "type": "security",
    "typeLabel": "ด่านตรวจยาเสพติดถาวร",
    "locationName": "ทล.1 พหลโยธิน กม.595 ต.พระบาทวังตวง อ.แม่พริก",
    "province": "ลำปาง",
    "district": "แม่พริก",
    "lat": 17.435,
    "lng": 99.125,
    "direction": "ขาล่องลงใต้",
    "status": "active",
    "verifiedCount": 110,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:10:00+07:00",
    "description": "ด่านตรวจถาวรแม่พริก ประตูด่านตรวจสำคัญที่สุดบนถนนพหลโยธิน มีเครื่องตรวจสแกนรถบรรทุก",
    "reportedBy": "สภ.แม่พริก",
    "severity": "high"
  },
  {
    "id": "cp-pre-01",
    "title": "ด่านตรวจถาวรห้วยไร่ ทล.11 กม.362 เด่นชัย",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.11 กม.362 ต.ห้วยไร่ อ.เด่นชัย",
    "province": "แพร่",
    "district": "เด่นชัย",
    "lat": 17.852,
    "lng": 100.082,
    "direction": "ขาล่องลง กทม./อุตรดิตถ์",
    "status": "active",
    "verifiedCount": 135,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:00:00+07:00",
    "description": "ด่านตรวจใหญ่สายเอเชียตะวันออกเฉียงเหนือ ทล.11 ตรวจจับยาเสพติดและสิ่งของผิดกฎหมายตลอด 24 ชม.",
    "reportedBy": "สภ.ห้วยไร่ ภ.จว.แพร่",
    "severity": "high"
  },
  {
    "id": "cp-nan-01",
    "title": "ด่านตรวจถาวรห้วยน้ำอุ่น ทล.101 อ.เวียงสา",
    "type": "security",
    "typeLabel": "ด่านตรวจสกัดเข้าน่าน",
    "locationName": "ทล.101 ร้องกวาง-น่าน กม.278 ต.อ่ายนาไลย อ.เวียงสา",
    "province": "น่าน",
    "district": "เวียงสา",
    "lat": 18.528,
    "lng": 100.675,
    "direction": "ทั้งสองฝั่ง (เข้า-ออก จ.น่าน)",
    "status": "active",
    "verifiedCount": 78,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:05:00+07:00",
    "description": "ประตูด่านตรวจหลักเข้าสู่ จ.น่าน ตรวจสอบความมั่นคง สิ่งผิดกฎหมาย และดูแลนักท่องเที่ยว",
    "reportedBy": "สภ.เวียงสา ภ.จว.น่าน",
    "severity": "medium"
  },
  {
    "id": "cp-pyo-01",
    "title": "จุดตรวจถาวรแม่ต๋ำ ทล.1 พหลโยธิน กม.835",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง & วินัยจราจร",
    "locationName": "ทล.1 พหลโยธิน กม.835 แยกแม่ต๋ำ อ.เมืองพะเยา",
    "province": "พะเยา",
    "district": "เมืองพะเยา",
    "lat": 19.145,
    "lng": 99.918,
    "direction": "ขาขึ้นเชียงราย",
    "status": "active",
    "verifiedCount": 53,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T10:40:00+07:00",
    "description": "จุดตรวจความมั่นคง สภ.แม่ต๋ำ ตรวจสอบรถยนต์ รถโดยสาร และกวดขันวินัยจราจร",
    "reportedBy": "สภ.แม่ต๋ำ",
    "severity": "medium"
  },
  {
    "id": "cp-msn-01",
    "title": "จุดตรวจถาวรแม่ปิง ทล.108 อ.ปาย",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & บุคคลต่างด้าว",
    "locationName": "ทล.108 เชียงใหม่-แม่ฮ่องสอน กม.182 ต.แม่ปี้ง อ.ปาย",
    "province": "แม่ฮ่องสอน",
    "district": "ปาย",
    "lat": 19.352,
    "lng": 98.435,
    "direction": "ขาเข้า อ.ปาย",
    "status": "active",
    "verifiedCount": 62,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:45:00+07:00",
    "description": "ด่านตรวจบูรณาการตรวจบุคคลเข้าเมือง ยาเสพติด และดูแลอำนวยความสะดวกนักท่องเที่ยวเส้นทาง 762 โค้ง",
    "reportedBy": "สภ.ปาย & ตชด.336",
    "severity": "high"
  },
  {
    "id": "cp-utd-01",
    "title": "จุดตรวจตำรวจทางหลวงวังสีสูบ ทล.11 แยกวังสีสูบ",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.11 พืชลาน-อุตรดิตถ์ กม.314 แยกวังสีสูบ",
    "province": "อุตรดิตถ์",
    "district": "เมืองอุตรดิตถ์",
    "lat": 17.652,
    "lng": 100.118,
    "direction": "ขาขึ้นเด่นชัย-แพร่",
    "status": "active",
    "verifiedCount": 42,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:25:00+07:00",
    "description": "จุดตรวจกวดขันวินัยจราจร เตือนความเร็วช่วงก่อนขึ้นเขาพลึง",
    "reportedBy": "ตำรวจทางหลวงอุตรดิตถ์",
    "severity": "medium"
  },
  {
    "id": "cp-plk-01",
    "title": "จุดตรวจความมั่นคงและจราจร ทล.12 สี่แยกอินโดจีน",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร & ตรวจจับความเร็ว",
    "locationName": "ทล.12 ตัด ทล.11 สี่แยกอินโดจีน อ.เมืองพิษณุโลก",
    "province": "พิษณุโลก",
    "district": "เมืองพิษณุโลก",
    "lat": 16.828,
    "lng": 100.325,
    "direction": "มุ่งหน้าหล่มสัก/วังทอง",
    "status": "active",
    "verifiedCount": 70,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T09:30:00+07:00",
    "description": "จุดตัดเส้นทางระเบียงเศรษฐกิจตะวันออก-ตะวันตก (EWEC) ตรวจวินัยจราจรและจับความเร็ว",
    "reportedBy": "สภ.เมืองพิษณุโลก",
    "severity": "high"
  },
  {
    "id": "cp-skt-01",
    "title": "จุดตรวจกวดขันวินัยจราจร สภ.เมืองสุโขทัย ทล.12",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.12 สุโขทัย-ตาก กม.165 ต.บ้านกล้วย",
    "province": "สุโขทัย",
    "district": "เมืองสุโขทัย",
    "lat": 17.008,
    "lng": 99.805,
    "direction": "ขาเข้าอุทยานประวัติศาสตร์สุโขทัย",
    "status": "active",
    "verifiedCount": 36,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:50:00+07:00",
    "description": "ตรวจหมวกกันน็อก ใบขับขี่ และอำนวยความสะดวกเส้นทางท่องเที่ยว",
    "reportedBy": "สภ.เมืองสุโขทัย",
    "severity": "low"
  },
  {
    "id": "cp-pct-01",
    "title": "จุดตรวจตำรวจทางหลวงสากเหล็ก ทล.11 กม.135",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.11 สากเหล็ก-วังทอง กม.135 แยกสากเหล็ก",
    "province": "พิจิตร",
    "district": "สากเหล็ก",
    "lat": 16.512,
    "lng": 100.528,
    "direction": "ขาขึ้นพิษณุโลก",
    "status": "active",
    "verifiedCount": 33,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:40:00+07:00",
    "description": "ตรวจความพร้อมรถบรรทุกและการใช้ความเร็วบนทางหลวงสาย 11",
    "reportedBy": "ตำรวจทางหลวงพิจิตร",
    "severity": "medium"
  },
  {
    "id": "cp-kpt-01",
    "title": "ด่านตรวจตำรวจทางหลวงสลกบาตร ทล.1 พหลโยธิน กม.390",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง & จับความเร็ว",
    "locationName": "ทล.1 พหลโยธิน กม.390 ต.สลกบาตร อ.ขาณุวรลักษบุรี",
    "province": "กำแพงเพชร",
    "district": "ขาณุวรลักษบุรี",
    "lat": 16.035,
    "lng": 99.815,
    "direction": "ขาขึ้นเหนือ",
    "status": "active",
    "verifiedCount": 68,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T08:45:00+07:00",
    "description": "จุดตรวจถาวรตำรวจทางหลวงสลกบาตร ตรวจจับความเร็ว ป้องกันอุบัติเหตุหลับใน",
    "reportedBy": "ส.ทล.1 กก.5 บก.ทล.",
    "severity": "high"
  },
  {
    "id": "cp-nsn-01",
    "title": "ด่านตรวจถาวรพยุหะคีรี ทล.1 พหลโยธิน กม.332",
    "type": "security",
    "typeLabel": "ประตูด่านตรวจภาคเหนือ",
    "locationName": "ทล.1 พหลโยธิน กม.332 ต.ย่านมัทรี อ.พยุหะคีรี",
    "province": "นครสวรรค์",
    "district": "พยุหะคีรี",
    "lat": 15.485,
    "lng": 100.135,
    "direction": "ขาล่องลง กทม.",
    "status": "active",
    "verifiedCount": 142,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:15:00+07:00",
    "description": "ด่านตรวจบูรณาการพยุหะคีรี ประตูหลักภาคเหนือสู่ภาคกลาง สกัดจับยาเสพติดและอาวุธตลอด 24 ชม.",
    "reportedBy": "สภ.พยุหะคีรี ภ.จว.นครสวรรค์",
    "severity": "high"
  },
  {
    "id": "cp-nsn-02",
    "title": "กล้องตรวจจับความเร็ว ทางเลี่ยงเมืองนครสวรรค์ ทล.122",
    "type": "speed_camera",
    "typeLabel": "กล้องจับความเร็ว",
    "locationName": "ทล.122 บายพาสนครสวรรค์ กม.8 สะพานข้ามแม่น้ำเจ้าพระยา",
    "province": "นครสวรรค์",
    "district": "เมืองนครสวรรค์",
    "lat": 15.685,
    "lng": 100.085,
    "direction": "ขาขึ้นพิษณุโลก/กำแพงเพชร",
    "status": "active",
    "verifiedCount": 89,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T07:50:00+07:00",
    "description": "กล้องตรวจจับความเร็วอัตโนมัติบนทางเลี่ยงเมือง จำกัด 90 กม./ชม.",
    "reportedBy": "ตำรวจทางหลวงนครสวรรค์",
    "severity": "high"
  },
  {
    "id": "cp-uti-01",
    "title": "จุดตรวจกวดขันวินัยจราจร สภ.เมืองอุทัยธานี ทล.333",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.333 กม.14 หน้าสวนน้ำเฉลิมพระเกียรติ",
    "province": "อุทัยธานี",
    "district": "เมืองอุทัยธานี",
    "lat": 15.378,
    "lng": 100.021,
    "direction": "ขาเข้าตัวเมืองอุทัยธานี",
    "status": "active",
    "verifiedCount": 28,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:35:00+07:00",
    "description": "ตรวจหมวกนิรภัย ป้ายทะเบียน และใบอนุญาตขับขี่",
    "reportedBy": "สภ.เมืองอุทัยธานี",
    "severity": "low"
  },
  {
    "id": "cp-pet-01",
    "title": "จุดตรวจตำรวจทางหลวงนาเฉลียง ทล.21 สระบุรี-หล่มสัก",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.21 กม.175 ต.นาเฉลียง อ.หนองไผ่",
    "province": "เพชรบูรณ์",
    "district": "หนองไผ่",
    "lat": 16.125,
    "lng": 101.115,
    "direction": "ขาขึ้นเขาค้อ/หล่มสัก",
    "status": "active",
    "verifiedCount": 58,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:25:00+07:00",
    "description": "จุดตรวจกวดขันวินัยจราจรและตรวจความพร้อมรถขึ้นภูเขาสูง",
    "reportedBy": "ส.ทล.5 กก.1 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-nma-01",
    "title": "ด่านตรวจถาวรคลองไผ่ ทล.2 มิตรภาพ กม.83 ริมลำตะคอง",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ตรวจจับความเร็ว",
    "locationName": "ถ.มิตรภาพ กม.83 ต.คลองไผ่ อ.สีคิ้ว",
    "province": "นครราชสีมา",
    "district": "สีคิ้ว",
    "lat": 14.865,
    "lng": 101.562,
    "direction": "ขาเข้าโคราช (มุ่งหน้าอีสาน)",
    "status": "active",
    "verifiedCount": 156,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T08:30:00+07:00",
    "description": "ประตูด่านตรวจใหญ่สู่ภาคอีสาน ตรวจยาเสพติด สิ่งผิดกฎหมาย และตรวจจับความเร็วลงเขา",
    "reportedBy": "สภ.คลองไผ่ & ตำรวจทางหลวงโคราช",
    "severity": "high"
  },
  {
    "id": "cp-nma-02",
    "title": "จุดตรวจตำรวจทางหลวงบ้านส้ม ทล.2 กม.180 โนนสูง",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง & ควันดำ",
    "locationName": "ถ.มิตรภาพ กม.180 ต.ธารปราสาท อ.โนนสูง",
    "province": "นครราชสีมา",
    "district": "โนนสูง",
    "lat": 15.195,
    "lng": 102.265,
    "direction": "ขาออก (มุ่งหน้าขอนแก่น)",
    "status": "active",
    "verifiedCount": 65,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:15:00+07:00",
    "description": "ตรวจกวดขันวินัยจราจรบน ถ.มิตรภาพ และตรวจวัดควันดำรถบรรทุก",
    "reportedBy": "ส.ทล.1 กก.6 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-kkn-01",
    "title": "ด่านตรวจตำรวจทางหลวงท่าพระ ทล.2 มิตรภาพ กม.320",
    "type": "speed_camera",
    "typeLabel": "ด่านตรวจทางหลวง & จับความเร็ว",
    "locationName": "ถ.มิตรภาพ กม.320 ต.ท่าพระ อ.เมืองขอนแก่น",
    "province": "ขอนแก่น",
    "district": "เมืองขอนแก่น",
    "lat": 16.335,
    "lng": 102.805,
    "direction": "ขาเข้าเมืองขอนแก่น",
    "status": "active",
    "verifiedCount": 94,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:10:00+07:00",
    "description": "ด่านตรวจหลักก่อนเข้าตัวเมืองขอนแก่น กล้องเรดาร์ตรวจจับความเร็วอัตโนมัติ 90 กม./ชม.",
    "reportedBy": "ส.ทล.2 กก.4 บก.ทล.",
    "severity": "high"
  },
  {
    "id": "cp-udn-01",
    "title": "จุดตรวจถาวรกุมภวาปี ทล.2 มิตรภาพ กม.420",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ถ.มิตรภาพ กม.420 ต.พันดอน อ.กุมภวาปี",
    "province": "อุดรธานี",
    "district": "กุมภวาปี",
    "lat": 17.118,
    "lng": 102.975,
    "direction": "ขาเข้าอุดรธานี",
    "status": "active",
    "verifiedCount": 82,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:40:00+07:00",
    "description": "ด่านตรวจความมั่นคง สภ.กุมภวาปี สกัดกั้นยาเสพติดตามแนวแม่น้ำโขง ตรวจค้นรถต้องสงสัย",
    "reportedBy": "สภ.กุมภวาปี",
    "severity": "high"
  },
  {
    "id": "cp-ubn-01",
    "title": "จุดตรวจบูรณาการ สภ.วารินชำราบ ทล.24 กม.415",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร & แอลกอฮอล์",
    "locationName": "ทล.24 เดชอุดม-อุบลฯ กม.415 ต.แสนสุข อ.วารินชำราบ",
    "province": "อุบลราชธานี",
    "district": "วารินชำราบ",
    "lat": 15.195,
    "lng": 104.855,
    "direction": "ขาเข้าเมืองอุบลราชธานี",
    "status": "active",
    "verifiedCount": 61,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T10:45:00+07:00",
    "description": "ด่านตรวจทางเข้าเมืองอุบลฯ ตรวจวัดแอลกอฮอล์ หมวกกันน็อก และความเร็ว",
    "reportedBy": "สภ.วารินชำราบ",
    "severity": "medium"
  },
  {
    "id": "cp-brm-01",
    "title": "จุดตรวจตำรวจทางหลวงนางรอง ทล.24 กม.92",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.24 สีคิ้ว-อุบลฯ กม.92 แยกนางรอง",
    "province": "บุรีรัมย์",
    "district": "นางรอง",
    "lat": 14.632,
    "lng": 102.795,
    "direction": "ขาออก (มุ่งหน้าสุรินทร์)",
    "status": "active",
    "verifiedCount": 47,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:50:00+07:00",
    "description": "ตรวจความพร้อมรถโดยสารและยานพาหนะบนเส้นทางอีสานใต้สาย 24",
    "reportedBy": "ตำรวจทางหลวงบุรีรัมย์",
    "severity": "medium"
  },
  {
    "id": "cp-srn-01",
    "title": "จุดตรวจตำรวจทางหลวงปราสาท ทล.24 กม.150 แยกปราสาท",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.24 ตัด ทล.214 แยกปราสาท อ.ปราสาท",
    "province": "สุรินทร์",
    "district": "ปราสาท",
    "lat": 14.645,
    "lng": 103.405,
    "direction": "ทั้งสองฝั่ง",
    "status": "active",
    "verifiedCount": 51,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:00:00+07:00",
    "description": "จุดตัดหลักอีสานใต้ มุ่งหน้าช่องจอม ชายแดนกัมพูชา ตรวจความมั่นคงและจราจร",
    "reportedBy": "ส.ทล.3 กก.6 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-ssk-01",
    "title": "จุดตรวจความมั่นคง ทล.24 กม.235 แยกหัวช้าง",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & จราจร",
    "locationName": "ทล.24 กม.235 แยกหัวช้าง อ.อุทุมพรพิสัย",
    "province": "ศรีสะเกษ",
    "district": "อุทุมพรพิสัย",
    "lat": 15.112,
    "lng": 104.145,
    "direction": "ขาเข้าอุบลราชธานี",
    "status": "active",
    "verifiedCount": 43,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T10:30:00+07:00",
    "description": "ด่านตรวจความมั่นคง สภ.อุทุมพรพิสัย กวดขันวินัยจราจรและตรวจค้นสิ่งผิดกฎหมาย",
    "reportedBy": "สภ.อุทุมพรพิสัย",
    "severity": "medium"
  },
  {
    "id": "cp-ret-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.23 ถ.แจ้งสนิท หน้า มรภ.ร้อยเอ็ด",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.23 ถ.แจ้งสนิท ต.เกาะแก้ว อ.เสลภูมิ",
    "province": "ร้อยเอ็ด",
    "district": "เสลภูมิ",
    "lat": 16.042,
    "lng": 103.785,
    "direction": "ขาออก มุ่งหน้ายโสธร",
    "status": "active",
    "verifiedCount": 37,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T11:00:00+07:00",
    "description": "ตรวจหมวกกันน็อก ใบขับขี่ และเข็มขัดนิรภัย",
    "reportedBy": "สภ.เสลภูมิ",
    "severity": "low"
  },
  {
    "id": "cp-cpm-01",
    "title": "จุดตรวจตำรวจทางหลวงจัตุรัส ทล.201 กม.105",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.201 สีคิ้ว-ชัยภูมิ กม.105 อ.จัตุรัส",
    "province": "ชัยภูมิ",
    "district": "จัตุรัส",
    "lat": 15.568,
    "lng": 101.835,
    "direction": "ขาเข้าเมืองชัยภูมิ",
    "status": "active",
    "verifiedCount": 45,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:35:00+07:00",
    "description": "จุดตรวจเส้นทางหลักเข้าสู่ จ.ชัยภูมิ ตรวจวัดความเร็วและตรวจหาสารเสพติด",
    "reportedBy": "ตำรวจทางหลวงชัยภูมิ",
    "severity": "medium"
  },
  {
    "id": "cp-mkm-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.213 มหาสารคาม-กาฬสินธุ์",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.213 กม.12 อ.กันทรวิชัย",
    "province": "มหาสารคาม",
    "district": "กันทรวิชัย",
    "lat": 16.295,
    "lng": 103.312,
    "direction": "ขาออก มุ่งหน้ากาฬสินธุ์",
    "status": "active",
    "verifiedCount": 39,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:15:00+07:00",
    "description": "ตรวจป้ายทะเบียน ใบอนุญาตขับขี่ และกวดขันหมวกนิรภัย",
    "reportedBy": "สภ.กันทรวิชัย",
    "severity": "low"
  },
  {
    "id": "cp-ksn-01",
    "title": "จุดตรวจตำรวจทางหลวงยางตลาด ทล.12 กม.315",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.12 ขอนแก่น-กาฬสินธุ์ กม.315 สี่แยกยางตลาด",
    "province": "กาฬสินธุ์",
    "district": "ยางตลาด",
    "lat": 16.402,
    "lng": 103.375,
    "direction": "ขาเข้าเมืองกาฬสินธุ์",
    "status": "active",
    "verifiedCount": 54,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:20:00+07:00",
    "description": "จุดตรวจบนทางหลวงสายเศรษฐกิจตะวันออก-ตะวันตก ตรวจสอบความพร้อมผู้ขับขี่",
    "reportedBy": "ส.ทล.2 กก.4 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-snk-01",
    "title": "จุดตรวจถาวรคำหอม ทล.213 เทือกเขาภูพาน",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงภูพาน",
    "locationName": "ทล.213 สกลนคร-กาฬสินธุ์ กม.142 ต.ห้วยยาง อ.เมืองสกลนคร",
    "province": "สกลนคร",
    "district": "เมืองสกลนคร",
    "lat": 17.112,
    "lng": 104.085,
    "direction": "ทั้งสองฝั่ง (ข้ามเขาภูพาน)",
    "status": "active",
    "verifiedCount": 74,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:05:00+07:00",
    "description": "ด่านตรวจถาวรบนเทือกเขาภูพาน สกัดกั้นไม้พะยูง ยาเสพติด และตรวจสอบรถยนต์ข้ามเขา",
    "reportedBy": "สภ.เมืองสกลนคร & ตชด.23",
    "severity": "high"
  },
  {
    "id": "cp-npm-01",
    "title": "จุดตรวจความมั่นคง สะพานมิตรภาพไทย-ลาว 3 ทล.212",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงชายแดน",
    "locationName": "ทล.212 เลี่ยงเมืองนครพนม ทางเข้าสะพานมิตรภาพ 3",
    "province": "นครพนม",
    "district": "เมืองนครพนม",
    "lat": 17.485,
    "lng": 104.725,
    "direction": "ขาออกสู่สะพานมิตรภาพ",
    "status": "active",
    "verifiedCount": 68,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:50:00+07:00",
    "description": "ด่านตรวจความมั่นคงชายแดน ตรวจสอบสินค้าหนีภาษี เอกสารผ่านแดน และยาเสพติด",
    "reportedBy": "สภ.เมืองนครพนม & ตม.นครพนม",
    "severity": "high"
  },
  {
    "id": "cp-mdh-01",
    "title": "จุดตรวจบูรณาการสะพานมิตรภาพ 2 ทล.212 มุกดาหาร",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงสะพานมิตรภาพ",
    "locationName": "ทล.212 ชยางกูร ทางเข้าสะพานมิตรภาพ 2 อ.เมืองมุกดาหาร",
    "province": "มุกดาหาร",
    "district": "เมืองมุกดาหาร",
    "lat": 16.602,
    "lng": 104.745,
    "direction": "ขาเข้า-ออก ด่านชายแดน",
    "status": "active",
    "verifiedCount": 59,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:10:00+07:00",
    "description": "ตรวจค้นยานพาหนะและสิ่งผิดกฎหมายตามแนวแม่น้ำโขงและเส้นทางเชื่อมต่อ สปป.ลาว",
    "reportedBy": "สภ.เมืองมุกดาหาร",
    "severity": "high"
  },
  {
    "id": "cp-yst-01",
    "title": "จุดตรวจกวดขันวินัยจราจร สภ.เมืองยโสธร ทล.23",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.23 ถ.แจ้งสนิท กม.182 ต.ตาดทอง อ.เมืองยโสธร",
    "province": "ยโสธร",
    "district": "เมืองยโสธร",
    "lat": 15.775,
    "lng": 104.162,
    "direction": "ขาออก มุ่งหน้าอุบลราชธานี",
    "status": "active",
    "verifiedCount": 32,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:40:00+07:00",
    "description": "ตรวจกวดขันหมวกนิรภัย เข็มขัดนิรภัย และใบขับขี่",
    "reportedBy": "สภ.เมืองยโสธร",
    "severity": "low"
  },
  {
    "id": "cp-acr-01",
    "title": "จุดตรวจตำรวจทางหลวงอำนาจเจริญ ทล.212 ชยางกูร",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.212 ชยางกูร กม.340 ต.โนนหนามแท่ง",
    "province": "อำนาจเจริญ",
    "district": "เมืองอำนาจเจริญ",
    "lat": 15.895,
    "lng": 104.645,
    "direction": "ขาเข้าเมืองอำนาจเจริญ",
    "status": "active",
    "verifiedCount": 28,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T11:10:00+07:00",
    "description": "ตรวจความพร้อมของผู้ขับขี่ กวดขันการใช้ความเร็วบนทางหลวงสาย 212",
    "reportedBy": "ตำรวจทางหลวงอำนาจเจริญ",
    "severity": "medium"
  },
  {
    "id": "cp-nki-01",
    "title": "ด่านตรวจหนองสองห้อง ทล.2 มิตรภาพ กม.485",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ถ.มิตรภาพ กม.485 ต.ค่ายบกหวาน อ.เมืองหนองคาย",
    "province": "หนองคาย",
    "district": "เมืองหนองคาย",
    "lat": 17.785,
    "lng": 102.772,
    "direction": "ขาล่องเข้าอุดรธานี",
    "status": "active",
    "verifiedCount": 98,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:15:00+07:00",
    "description": "ด่านตรวจใหญ่สายมิตรภาพ สกัดกั้นยาเสพติดและของเถื่อนจากชายแดนสะพานมิตรภาพไทย-ลาว",
    "reportedBy": "สภ.เมืองหนองคาย",
    "severity": "high"
  },
  {
    "id": "cp-bkn-01",
    "title": "จุดตรวจความมั่นคง ทล.212 บึงกาฬ-นครพนม",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงริมโขง",
    "locationName": "ทล.212 กม.135 ต.วิศิษฐ์ อ.เมืองบึงกาฬ",
    "province": "บึงกาฬ",
    "district": "เมืองบึงกาฬ",
    "lat": 18.358,
    "lng": 103.665,
    "direction": "เลียบแม่น้ำโขง",
    "status": "active",
    "verifiedCount": 45,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T10:20:00+07:00",
    "description": "ด่านตรวจบูรณาการตำรวจ ทหารพราน สกัดกั้นยาเสพติดตามแนวแม่น้ำโขง 24 ชม.",
    "reportedBy": "สภ.เมืองบึงกาฬ & นรข.เขตหนองคาย",
    "severity": "high"
  },
  {
    "id": "cp-nbp-01",
    "title": "จุดตรวจกวดขันวินัยจราจร ทล.210 หนองบัวลำภู-อุดรธานี",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทล.210 กม.44 หน้าศูนย์ราชการจังหวัดหนองบัวลำภู",
    "province": "หนองบัวลำภู",
    "district": "เมืองหนองบัวลำภู",
    "lat": 17.215,
    "lng": 102.435,
    "direction": "ขาเข้าเมือง",
    "status": "active",
    "verifiedCount": 31,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:45:00+07:00",
    "description": "ตรวจหมวกกันน็อก ใบขับขี่ และเข็มขัดนิรภัย",
    "reportedBy": "สภ.เมืองหนองบัวลำภู",
    "severity": "low"
  },
  {
    "id": "cp-lei-01",
    "title": "จุดตรวจตำรวจทางหลวงวังสะพุง ทล.201 กม.290",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.201 ชัยภูมิ-เลย กม.290 ต.วังสะพุง อ.วังสะพุง",
    "province": "เลย",
    "district": "วังสะพุง",
    "lat": 17.305,
    "lng": 101.765,
    "direction": "ขาเข้าเมืองเลย/เชียงคาน",
    "status": "active",
    "verifiedCount": 50,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:30:00+07:00",
    "description": "จุดตรวจความพร้อมผู้ขับขี่และยานพาหนะก่อนเข้าสู่เส้นทางท่องเที่ยวภูเขาของ จ.เลย",
    "reportedBy": "ตำรวจทางหลวงเลย",
    "severity": "medium"
  },
  {
    "id": "cp-cbi-01",
    "title": "กล้องตรวจจับความเร็ว มอเตอร์เวย์ สาย 7 กม.77 บางพระ-พัทยา",
    "type": "speed_camera",
    "typeLabel": "กล้องจับความเร็ว มอเตอร์เวย์",
    "locationName": "ทล.พิเศษหมายเลข 7 (มอเตอร์เวย์) กม.77 ต.บางพระ",
    "province": "ชลบุรี",
    "district": "ศรีราชา",
    "lat": 13.215,
    "lng": 100.975,
    "direction": "ขาออก (มุ่งหน้าพัทยา/มาบตาพุด)",
    "status": "active",
    "verifiedCount": 140,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:00:00+07:00",
    "description": "กล้องเรดาร์ความเร็วอัตโนมัติ 24 ชม. จำกัดความเร็ว 120 กม./ชม. เลนขวาสุด",
    "reportedBy": "ส.ทล.1 กก.8 บก.ทล. (มอเตอร์เวย์)",
    "severity": "high"
  },
  {
    "id": "cp-cbi-02",
    "title": "จุดตรวจวัดแอลกอฮอล์ ถ.สุขุมวิท พัทยากลาง",
    "type": "alcohol",
    "typeLabel": "ตรวจแอลกอฮอล์ & จราจร",
    "locationName": "ถ.สุขุมวิท กม.144 หน้าปั๊ม ปตท. พัทยากลาง",
    "province": "ชลบุรี",
    "district": "บางละมุง",
    "lat": 12.932,
    "lng": 100.898,
    "direction": "ขาเข้าสัตหีบ",
    "status": "active",
    "verifiedCount": 85,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T11:30:00+07:00",
    "description": "ตรวจเป่าแอลกอฮอล์ กวดขันวินัยจราจร และตรวจค้นอาวุธในเขตท่องเที่ยวพัทยา",
    "reportedBy": "สภ.เมืองพัทยา",
    "severity": "high"
  },
  {
    "id": "cp-ryg-01",
    "title": "จุดตรวจตำรวจทางหลวงแกลง ทล.3 ถ.สุขุมวิท กม.268",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.3 สุขุมวิท กม.268 สี่แยกประแสร์ อ.แกลง",
    "province": "ระยอง",
    "district": "แกลง",
    "lat": 12.782,
    "lng": 101.652,
    "direction": "ขาออก มุ่งหน้าจันทบุรี",
    "status": "active",
    "verifiedCount": 56,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:15:00+07:00",
    "description": "ตรวจกวดขันการใช้ความเร็ว รถโดยสารสาธารณะ และตรวจวัดแอลกอฮอล์",
    "reportedBy": "ตำรวจทางหลวงระยอง",
    "severity": "medium"
  },
  {
    "id": "cp-cti-01",
    "title": "จุดตรวจถาวรเนินสูง ทล.3 ถ.สุขุมวิท กม.318",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & จราจร",
    "locationName": "ทล.3 สุขุมวิท กม.318 สี่แยกเนินสูง ต.เขาวัว อ.ท่าใหม่",
    "province": "จันทบุรี",
    "district": "ท่าใหม่",
    "lat": 12.675,
    "lng": 102.045,
    "direction": "ขาเข้าเมืองจันทบุรี",
    "status": "active",
    "verifiedCount": 73,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:45:00+07:00",
    "description": "ประตูด่านตรวจสำคัญของ จ.จันทบุรี ตรวจสอบยาเสพติด บุคคลต่างด้าว และวินัยจราจร",
    "reportedBy": "สภ.ท่าใหม่ ภ.จว.จันทบุรี",
    "severity": "high"
  },
  {
    "id": "cp-trt-01",
    "title": "ด่านตรวจถาวรบ้านท่าจอด ทล.3 กม.385 เขาสมิง",
    "type": "security",
    "typeLabel": "ประตูด่านตรวจเข้าตราด",
    "locationName": "ทล.3 สุขุมวิท กม.385 เชิงสะพานท่าจอด ต.แสนตุ้ง อ.เขาสมิง",
    "province": "ตราด",
    "district": "เขาสมิง",
    "lat": 12.385,
    "lng": 102.345,
    "direction": "ขาเข้าตัวเมืองตราดและท่าเรือเกาะช้าง",
    "status": "active",
    "verifiedCount": 86,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:00:00+07:00",
    "description": "ด่านตรวจถาวรจุดแรกสู่ จ.ตราด สกัดกั้นยาเสพติด สินค้าหนีภาษี และดูแลนักท่องเที่ยวไปเกาะช้าง/เกาะกูด",
    "reportedBy": "สภ.เขาสมิง & นปพ.ตราด",
    "severity": "high"
  },
  {
    "id": "cp-cco-01",
    "title": "กล้องตรวจจับความเร็ว ทล.314 สิริโสธร กม.12 บางปะกง",
    "type": "speed_camera",
    "typeLabel": "กล้องตรวจจับความเร็ว",
    "locationName": "ทล.314 บางปะกง-ฉะเชิงเทรา กม.12 ต.ท่าสะอ้าน",
    "province": "ฉะเชิงเทรา",
    "district": "บางปะกง",
    "lat": 13.585,
    "lng": 101.025,
    "direction": "ขาเข้าเมืองฉะเชิงเทรา (มุ่งหน้าวัดหลวงพ่อโสธร)",
    "status": "active",
    "verifiedCount": 91,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:20:00+07:00",
    "description": "กล้องตรวจจับความเร็วอัตโนมัติ จำกัด 90 กม./ชม. บนเส้นทางเชื่อมมอเตอร์เวย์เข้าแปดริ้ว",
    "reportedBy": "สภ.บางปะกง",
    "severity": "high"
  },
  {
    "id": "cp-pri-01",
    "title": "จุดตรวจตำรวจทางหลวงกบินทร์บุรี ทล.304 กม.165",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.304 กบินทร์บุรี-ปักธงชัย กม.165 แยกกบินทร์บุรี",
    "province": "ปราจีนบุรี",
    "district": "กบินทร์บุรี",
    "lat": 13.985,
    "lng": 101.765,
    "direction": "ขาขึ้นเขาปักธงชัย (มุ่งหน้านครราชสีมา)",
    "status": "active",
    "verifiedCount": 63,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:05:00+07:00",
    "description": "ตรวจความพร้อมเบรกและเครื่องยนต์ของรถบรรทุกก่อนขึ้นเขาศาลเจ้าพ่อปู่โทน ทล.304",
    "reportedBy": "ตำรวจทางหลวงปราจีนบุรี",
    "severity": "high"
  },
  {
    "id": "cp-skw-01",
    "title": "ด่านตรวจถาวรคลองลึก ทล.33 อ.อรัญประเทศ",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงชายแดนไทย-กัมพูชา",
    "locationName": "ทล.33 สุวรรณศร ทางเข้าตลาดโรงเกลือ อ.อรัญประเทศ",
    "province": "สระแก้ว",
    "district": "อรัญประเทศ",
    "lat": 13.682,
    "lng": 102.515,
    "direction": "ทั้งสองฝั่ง",
    "status": "active",
    "verifiedCount": 97,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T08:40:00+07:00",
    "description": "ด่านตรวจร่วมตำรวจ ทหารพราน ตรวจสอบสินค้าละเมิดลิขสิทธิ์ ยาเสพติด และการลักลอบข้ามแดน",
    "reportedBy": "สภ.คลองลึก & กองร้อย ทพ.1201",
    "severity": "high"
  },
  {
    "id": "cp-rbr-01",
    "title": "จุดตรวจตำรวจทางหลวงวังมะนาว ทล.4 เพชรเกษม กม.125",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.4 ตัด ทล.35 แยกวังมะนาว อ.ปากท่อ",
    "province": "ราชบุรี",
    "district": "ปากท่อ",
    "lat": 13.315,
    "lng": 99.825,
    "direction": "ขาล่องใต้ (มุ่งหน้าเพชรบุรี)",
    "status": "active",
    "verifiedCount": 115,
    "clearedCount": 2,
    "reportedAt": "2026-09-29T09:10:00+07:00",
    "description": "จุดตัดหลักจาก ถ.พระราม 2 และ ถ.เพชรเกษม รวมสู่ภาคใต้ ตรวจจับความเร็วและกวดขันวินัยจราจร",
    "reportedBy": "ส.ทล.2 กก.2 บก.ทล.",
    "severity": "high"
  },
  {
    "id": "cp-kri-01",
    "title": "จุดตรวจความมั่นคงไทรโยค ทล.323 กม.110 กาญจนบุรี",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงชายแดน",
    "locationName": "ทล.323 แสงชูโต กม.110 อ.ไทรโยค",
    "province": "กาญจนบุรี",
    "district": "ไทรโยค",
    "lat": 14.285,
    "lng": 98.985,
    "direction": "ขาเข้าเมืองกาญจนบุรี",
    "status": "active",
    "verifiedCount": 79,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:50:00+07:00",
    "description": "ด่านตรวจสกัดแรงงานต่างด้าวผิดกฎหมาย ยาเสพติด และอาวุธตามแนวชายแดนตะวันตก",
    "reportedBy": "สภ.ไทรโยค & ตชด.136",
    "severity": "high"
  },
  {
    "id": "cp-tak-01",
    "title": "ด่านตรวจถาวรห้วยยะอุ ทล.12 ตาก-แม่สอด กม.58",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.12 กม.58 ต.ด่านแม่ละเมา อ.แม่สอด",
    "province": "ตาก",
    "district": "แม่สอด",
    "lat": 16.782,
    "lng": 98.885,
    "direction": "ขาเข้าเมืองตาก",
    "status": "active",
    "verifiedCount": 130,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:30:00+07:00",
    "description": "ด่านตรวจค้นเข้มงวดระดับสูง รถยนต์ทุกคันต้องชะลอ ตรวจสกัดสิ่งผิดกฎหมายจากแนวชายแดนแม่สอด",
    "reportedBy": "สภ.พะวอ & ฉก.ร.14",
    "severity": "high"
  },
  {
    "id": "cp-pbi-01",
    "title": "ด่านตรวจตำรวจทางหลวงเขาย้อย ทล.4 เพชรเกษม กม.136",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง & ควันดำ",
    "locationName": "ทล.4 เพชรเกษม กม.136 อ.เขาย้อย",
    "province": "เพชรบุรี",
    "district": "เขาย้อย",
    "lat": 13.242,
    "lng": 99.835,
    "direction": "ขาล่องใต้",
    "status": "active",
    "verifiedCount": 84,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:20:00+07:00",
    "description": "ประตูด่านตรวจหลักสู่ 14 จังหวัดภาคใต้ ตรวจจับความเร็ว ตรวจควันดำ และป้องกันหลับใน",
    "reportedBy": "ส.ทล.2 กก.2 บก.ทล.",
    "severity": "high"
  },
  {
    "id": "cp-pkn-01",
    "title": "ด่านตรวจถาวรทับสะแก ทล.4 เพชรเกษม กม.352",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.4 เพชรเกษม กม.352 ต.แสงอรุณ อ.ทับสะแก",
    "province": "ประจวบคีรีขันธ์",
    "district": "ทับสะแก",
    "lat": 11.512,
    "lng": 99.645,
    "direction": "ทั้งสองฝั่ง (ขึ้นเหนือ - ล่องใต้)",
    "status": "active",
    "verifiedCount": 145,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:00:00+07:00",
    "description": "ด่านตรวจจุดคอดขอดภาคใต้ คัดกรองยาเสพติด อาวุธ และสิ่งของผิดกฎหมาย มีอุโมงค์เอ็กซเรย์",
    "reportedBy": "สภ.ทับสะแก ภ.จว.ประจวบคีรีขันธ์",
    "severity": "high"
  },
  {
    "id": "cp-cpn-01",
    "title": "ด่านตรวจถาวรบ้านพละ ทล.4 เพชรเกษม กม.445",
    "type": "security",
    "typeLabel": "ประตูด่านตรวจใหญ่ภาคใต้",
    "locationName": "ทล.4 เพชรเกษม กม.445 ต.เขาไชยราช อ.ท่าแซะ",
    "province": "ชุมพร",
    "district": "ท่าแซะ",
    "lat": 10.825,
    "lng": 99.315,
    "direction": "ขาล่องใต้ และขาขึ้น กทม.",
    "status": "active",
    "verifiedCount": 168,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:15:00+07:00",
    "description": "ด่านตรวจบูรณาการบ้านพละ ประตูเข้า-ออก 14 จังหวัดภาคใต้ ตรวจเข้มยาเสพติดและอาวุธ 24 ชม.",
    "reportedBy": "สภ.บ้านมาบอำมฤต & กก.สส.ภ.จว.ชุมพร",
    "severity": "high"
  },
  {
    "id": "cp-rng-01",
    "title": "ด่านตรวจศิลาสลัก จปร. ทล.4 เพชรเกษม อ.กระบุรี",
    "type": "security",
    "typeLabel": "ด่านความมั่นคงชายแดน",
    "locationName": "ทล.4 กม.535 ต.ปากจั่น อ.กระบุรี",
    "province": "ระนอง",
    "district": "กระบุรี",
    "lat": 10.358,
    "lng": 98.745,
    "direction": "ขาเข้าเมืองระนอง",
    "status": "active",
    "verifiedCount": 54,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:40:00+07:00",
    "description": "ด่านความมั่นคงแนวชายแดนแม่น้ำกระบุรี ตรวจสอบบุคคลเข้าเมืองและสิ่งผิดกฎหมาย",
    "reportedBy": "สภ.ปากจั่น & ฉก.ร.25",
    "severity": "high"
  },
  {
    "id": "cp-sni-01",
    "title": "ด่านตรวจตำรวจทางหลวงพุนพิน ทล.41 กม.72",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.41 แยก กม.0 พุนพิน อ.พุนพิน",
    "province": "สุราษฎร์ธานี",
    "district": "พุนพิน",
    "lat": 9.112,
    "lng": 99.215,
    "direction": "ขาล่องใต้ (มุ่งหน้านครศรีฯ/สงขลา)",
    "status": "active",
    "verifiedCount": 85,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:10:00+07:00",
    "description": "ศูนย์กลางแยกเส้นทางสู่ฝั่งอ่าวไทยและอันดามัน ตรวจจับความเร็วและกวดขันวินัยจราจร",
    "reportedBy": "ส.ทล.5 กก.2 บก.ทล.",
    "severity": "high"
  },
  {
    "id": "cp-sni-02",
    "title": "ด่านตรวจความมั่นคงบ้านส้อง ทล.41 กม.155",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง & ยาเสพติด",
    "locationName": "ทล.41 ต.บ้านส้อง อ.เวียงสระ",
    "province": "สุราษฎร์ธานี",
    "district": "เวียงสระ",
    "lat": 8.635,
    "lng": 99.365,
    "direction": "ขาล่องใต้",
    "status": "active",
    "verifiedCount": 73,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T10:20:00+07:00",
    "description": "ด่านตรวจสกัดยาเสพติดและตรวจค้นยานพาหนะต้องสงสัยก่อนเข้าเขต จ.นครศรีธรรมราช",
    "reportedBy": "สภ.เวียงสระ",
    "severity": "high"
  },
  {
    "id": "cp-pkt-01",
    "title": "ด่านตรวจภูเก็ต (ท่าฉัตรไชย) ทล.402 ประตูเข้าเกาะ",
    "type": "security",
    "typeLabel": "ด่านตรวจภูเก็ต (ตรวจเข้ม 24 ชม.)",
    "locationName": "ทล.402 ถ.เทพกระษัตรี ต.ไม้ขาว อ.ถลาง",
    "province": "ภูเก็ต",
    "district": "ถลาง",
    "lat": 8.198,
    "lng": 98.298,
    "direction": "ขาเข้าเกาะภูเก็ต (ข้ามสะพานท้าวเทพกระษัตรี)",
    "status": "active",
    "verifiedCount": 182,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T08:00:00+07:00",
    "description": "ประตูด่านตรวจทางบกแห่งเดียวเข้าเกาะภูเก็ต มีกล้อง AI สแกนป้ายทะเบียน ตรวจอาวุธ สารเสพติด และหมายจับ",
    "reportedBy": "สภ.ท่าฉัตรไชย ภ.จว.ภูเก็ต",
    "severity": "high"
  },
  {
    "id": "cp-pna-01",
    "title": "จุดตรวจตำรวจทางหลวงทับปุด ทล.415 พังงา",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.415 พังงา-ทับปุด กม.18 อ.ทับปุด",
    "province": "พังงา",
    "district": "ทับปุด",
    "lat": 8.525,
    "lng": 98.615,
    "direction": "ขาเข้าเมืองพังงา/ภูเก็ต",
    "status": "active",
    "verifiedCount": 42,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:30:00+07:00",
    "description": "จุดตรวจกวดขันวินัยจราจรและตรวจจับความเร็วบนเส้นทางเชื่อมกระบี่-พังงา",
    "reportedBy": "ตำรวจทางหลวงพังงา",
    "severity": "medium"
  },
  {
    "id": "cp-kbi-01",
    "title": "จุดตรวจถาวรคลองท่อม ทล.4 เพชรเกษม กม.998",
    "type": "security",
    "typeLabel": "ด่านตรวจความมั่นคง & จราจร",
    "locationName": "ทล.4 เพชรเกษม กม.998 อ.คลองท่อม",
    "province": "กระบี่",
    "district": "คลองท่อม",
    "lat": 7.935,
    "lng": 99.145,
    "direction": "ขาออก มุ่งหน้าตรัง",
    "status": "active",
    "verifiedCount": 58,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:40:00+07:00",
    "description": "ตรวจค้นสิ่งผิดกฎหมาย ยาเสพติด และอำนวยความสะดวกแก่นักท่องเที่ยวสายอันดามัน",
    "reportedBy": "สภ.คลองท่อม",
    "severity": "medium"
  },
  {
    "id": "cp-nsi-01",
    "title": "ด่านตรวจถาวรทุ่งสง ทล.41 แยกหนองหว้า",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง & ยาเสพติด",
    "locationName": "ทล.41 กม.235 สี่แยกหนองหว้า อ.ทุ่งสง",
    "province": "นครศรีธรรมราช",
    "district": "ทุ่งสง",
    "lat": 8.165,
    "lng": 99.685,
    "direction": "ขาล่องใต้ (มุ่งหน้าพัทลุง/สงขลา)",
    "status": "active",
    "verifiedCount": 88,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T09:15:00+07:00",
    "description": "ชุมทางคมนาคมใหญ่ภาคใต้ตอนกลาง ตรวจจับความเร็ว ตรวจรถบรรทุก และสกัดกั้นยาเสพติด",
    "reportedBy": "สภ.ทุ่งสง & ตำรวจทางหลวงนครศรีฯ",
    "severity": "high"
  },
  {
    "id": "cp-trg-01",
    "title": "จุดตรวจตำรวจทางหลวงนาโยง ทล.4 ตรัง-พัทลุง เชิงเขาพับผ้า",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง & เขาพับผ้า",
    "locationName": "ทล.4 เพชรเกษม กม.1085 ต.ละมอ อ.นาโยง",
    "province": "ตรัง",
    "district": "นาโยง",
    "lat": 7.558,
    "lng": 99.785,
    "direction": "ขาขึ้นเขาพับผ้ามุ่งหน้าพัทลุง",
    "status": "active",
    "verifiedCount": 49,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:10:00+07:00",
    "description": "เตือนความเร็วและตรวจความพร้อมของรถก่อนขึ้นเขาพับผ้า เส้นทางโค้งลาดชันสูง",
    "reportedBy": "ตำรวจทางหลวงตรัง",
    "severity": "high"
  },
  {
    "id": "cp-plg-01",
    "title": "จุดตรวจถาวรนาโหนด ทล.4 เพชรเกษม กม.1170",
    "type": "traffic",
    "typeLabel": "ด่านตรวจความมั่นคง & จราจร",
    "locationName": "ทล.4 เพชรเกษม กม.1170 ต.นาโหนด อ.เมืองพัทลุง",
    "province": "พัทลุง",
    "district": "เมืองพัทลุง",
    "lat": 7.525,
    "lng": 100.065,
    "direction": "ขาล่องใต้มุ่งหน้าหาดใหญ่/สงขลา",
    "status": "active",
    "verifiedCount": 67,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:30:00+07:00",
    "description": "ด่านตรวจสกัดความมั่นคง สภ.เมืองพัทลุง ตรวจค้นสิ่งผิดกฎหมายและกวดขันวินัยจราจร",
    "reportedBy": "สภ.เมืองพัทลุง",
    "severity": "medium"
  },
  {
    "id": "cp-ska-01",
    "title": "ด่านตรวจความมั่นคงควนมีด ทล.43 อ.จะนะ",
    "type": "security",
    "typeLabel": "ด่านความมั่นคง 4 อำเภอสงขลา",
    "locationName": "ทล.43 สงขลา-ปัตตานี กม.31 ต.จะโหนง อ.จะนะ",
    "province": "สงขลา",
    "district": "จะนะ",
    "lat": 7.025,
    "lng": 100.675,
    "direction": "ขาล่องเข้า 3 จังหวัดชายแดนใต้",
    "status": "active",
    "verifiedCount": 175,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:30:00+07:00",
    "description": "ด่านตรวจความมั่นคงสูงสุด มีระบบสแกนใบหน้า กล้องอ่านป้ายทะเบียน ตรวจอาวุธและวัตถุระเบิด",
    "reportedBy": "กอ.รมน.ภาค 4 สน. & สภ.ควนมีด",
    "severity": "high"
  },
  {
    "id": "cp-ska-02",
    "title": "จุดตรวจตำรวจทางหลวงคลองแงะ ทล.4 หาดใหญ่-สะเดา",
    "type": "traffic",
    "typeLabel": "ด่านตรวจทางหลวง",
    "locationName": "ทล.4 กม.1275 ต.พังลา อ.สะเดา",
    "province": "สงขลา",
    "district": "สะเดา",
    "lat": 6.815,
    "lng": 100.465,
    "direction": "มุ่งหน้าด่านชายแดนสะเดา (มาเลเซีย)",
    "status": "active",
    "verifiedCount": 62,
    "clearedCount": 1,
    "reportedAt": "2026-09-29T10:00:00+07:00",
    "description": "ตรวจจับความเร็ว ตรวจรถขนส่งข้ามแดน และกวดขันการกระทำผิดกฎหมาย",
    "reportedBy": "ส.ทล.3 กก.7 บก.ทล.",
    "severity": "medium"
  },
  {
    "id": "cp-stn-01",
    "title": "จุดตรวจถาวรควนกาหลง ทล.406 สงขลา-สตูล กม.78",
    "type": "security",
    "typeLabel": "ประตูด่านตรวจเข้าสตูล",
    "locationName": "ทล.406 กม.78 ต.ควนกาหลง อ.ควนกาหลง",
    "province": "สตูล",
    "district": "ควนกาหลง",
    "lat": 6.825,
    "lng": 100.115,
    "direction": "ขาเข้า จ.สตูล",
    "status": "active",
    "verifiedCount": 51,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T09:45:00+07:00",
    "description": "ด่านตรวจสกัดสิ่งผิดกฎหมาย ยาเสพติด และดูแลนักท่องเที่ยวเดินทางไปท่าเรือปากบารา/เกาะหลีเป๊ะ",
    "reportedBy": "สภ.ควนกาหลง",
    "severity": "medium"
  },
  {
    "id": "cp-ptn-01",
    "title": "ด่านตรวจถาวรเกาะหม้อแกง ทล.43 อ.หนองจิก",
    "type": "security",
    "typeLabel": "ด่านตรวจความมั่นคงหลักเข้า 3 จว.ใต้",
    "locationName": "ทล.43 สงขลา-ปัตตานี กม.75 ต.ท่ากำชำ อ.หนองจิก",
    "province": "ปัตตานี",
    "district": "หนองจิก",
    "lat": 6.885,
    "lng": 101.125,
    "direction": "ขาเข้าตัวเมืองปัตตานี",
    "status": "active",
    "verifiedCount": 190,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:00:00+07:00",
    "description": "ประตูด่านตรวจความมั่นคงหลักสู่สามจังหวัดชายแดนภาคใต้ ตรวจสอบบัตรประชาชน ยานพาหนะ และความปลอดภัย 24 ชม.",
    "reportedBy": "ฉก.ทพ.43 & กอ.รมน.ภาค 4 สน.",
    "severity": "high"
  },
  {
    "id": "cp-yla-01",
    "title": "ด่านตรวจถาวรขุนไวย์ ทล.410 อ.เมืองยะลา",
    "type": "security",
    "typeLabel": "ด่านตรวจความมั่นคงขุนไวย์",
    "locationName": "ทล.410 ถ.สุขยางค์ ทางเข้าเมืองยะลา ต.สะเตงนอก",
    "province": "ยะลา",
    "district": "เมืองยะลา",
    "lat": 6.525,
    "lng": 101.285,
    "direction": "ขาเข้าเมืองยะลา และมุ่งหน้าเบตง",
    "status": "active",
    "verifiedCount": 140,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:15:00+07:00",
    "description": "ด่านตรวจความมั่นคงบูรณาการ ทหาร ตำรวจ อส. ตรวจค้นยานพาหนะและบุคคลอย่างละเอียด",
    "reportedBy": "ฉก.ยะลา 91 & สภ.เมืองยะลา",
    "severity": "high"
  },
  {
    "id": "cp-nwt-01",
    "title": "ด่านตรวจถาวรบาตู ทล.42 อ.บาเจาะ",
    "type": "security",
    "typeLabel": "ด่านตรวจความมั่นคงบาตู",
    "locationName": "ทล.42 ปัตตานี-นราธิวาส กม.78 ต.บาเจาะ อ.บาเจาะ",
    "province": "นราธิวาส",
    "district": "บาเจาะ",
    "lat": 6.512,
    "lng": 101.655,
    "direction": "ขาเข้าเมืองนราธิวาส",
    "status": "active",
    "verifiedCount": 160,
    "clearedCount": 0,
    "reportedAt": "2026-09-29T08:30:00+07:00",
    "description": "ประตูด่านตรวจหลักสู่ จ.นราธิวาส ตรวจสอบความปลอดภัย ป้องกันเหตุความไม่สงบตลอด 24 ชั่วโมง",
    "reportedBy": "ฉก.นย.ทร. & สภ.บาเจาะ",
    "severity": "high"
  }
];

window.MOCK_CHECKPOINTS = window.INITIAL_CHECKPOINTS;
