// Mock initial dataset for offline/file:// protocol fallback (Nationwide Thailand Checkpoints)
window.INITIAL_CHECKPOINTS = [
  {
    "id": "cp-101",
    "title": "ด่านตรวจวัดแอลกอฮอล์ ถ.รัชดาภิเษก",
    "type": "alcohol",
    "typeLabel": "ตรวจวัดแอลกอฮอล์",
    "locationName": "หน้า The Street รัชดา มุ่งหน้าแยกห้วยขวาง",
    "province": "กรุงเทพมหานคร",
    "district": "ดินแดง",
    "lat": 13.7709,
    "lng": 100.5735,
    "direction": "ขาออก (มุ่งหน้าแยกสุทธิสาร)",
    "status": "active",
    "verifiedCount": 58,
    "clearedCount": 2,
    "reportedAt": "2026-09-28T10:45:00+07:00",
    "description": "เจ้าหน้าที่ 8 นาย มีเต็นท์ตรวจเป่าแอลกอฮอล์ บีบเหลือ 1 ช่องทางขวาสุด",
    "reportedBy": "พลเมืองดี_Ratchada",
    "severity": "high"
  },
  {
    "id": "cp-102",
    "title": "ด่านกวดขันวินัยจราจร สี่แยกอโศก-สุขุมวิท",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ใต้ BTS อโศก ถ.สุขุมวิท",
    "province": "กรุงเทพมหานคร",
    "district": "คลองเตย",
    "lat": 13.7372,
    "lng": 100.5604,
    "direction": "ขาเข้า (มุ่งหน้าเพลินจิต)",
    "status": "active",
    "verifiedCount": 34,
    "clearedCount": 4,
    "reportedAt": "2026-09-28T10:20:00+07:00",
    "description": "ตรวจหมวกกันน็อก ป้ายภาษี ใบขับขี่ รถจักรยานยนต์วิ่งเลนขวา",
    "reportedBy": "Rider_Sukhumvit",
    "severity": "medium"
  },
  {
    "id": "cp-103",
    "title": "จุดตรวจควันดำและมลพิษ ถ.วิภาวดีรังสิต",
    "type": "smoke",
    "typeLabel": "ตรวจควันดำ/มลพิษ",
    "locationName": "วิภาวดีรังสิต หน้าโรงเรียนสุรศักดิ์มนตรี",
    "province": "กรุงเทพมหานคร",
    "district": "พญาไท",
    "lat": 13.7820,
    "lng": 100.5592,
    "direction": "ขาออก (คู่ขนาน)",
    "status": "active",
    "verifiedCount": 27,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T09:50:00+07:00",
    "description": "กรมควบคุมมลพิษร่วมกับตำรวจจราจร โบกรถกระบะและรถบรรทุกตรวจควันดำ",
    "reportedBy": "TruckWatcher_TH",
    "severity": "medium"
  },
  {
    "id": "cp-104",
    "title": "กล้องตรวจจับความเร็ว ถ.กาญจนาภิเษก (วงแหวนตะวันตก)",
    "type": "speed",
    "typeLabel": "กล้องจับความเร็ว",
    "locationName": "ถ.กาญจนาภิเษก กม.28 หน้าเซ็นทรัลเวสต์เกต",
    "province": "นนทบุรี",
    "district": "บางใหญ่",
    "lat": 13.8761,
    "lng": 100.4109,
    "direction": "ทั้งสองฝั่ง (จำกัด 90 กม./ชม.)",
    "status": "active",
    "verifiedCount": 92,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T08:00:00+07:00",
    "description": "กล้องเรดาร์เลเซอร์จับความเร็วตลอด 24 ชม. และตรวจจับเปลี่ยนเลนเส้นทึบ",
    "reportedBy": "ระบบอัตโนมัติ_Highway",
    "severity": "low"
  },
  {
    "id": "cp-105",
    "title": "ด่านตรวจร่วมความมั่นคง ถ.พระราม 2",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ถ.พระราม 2 ขาเข้า หน้าโลตัสพระราม 2",
    "province": "กรุงเทพมหานคร",
    "district": "บางขุนเทียน",
    "lat": 13.6627,
    "lng": 100.4398,
    "direction": "ขาเข้า (มุ่งหน้าดาวคะนอง)",
    "status": "active",
    "verifiedCount": 45,
    "clearedCount": 6,
    "reportedAt": "2026-09-28T10:15:00+07:00",
    "description": "ตรวจค้นสิ่งผิดกฎหมาย อาวุธ และตรวจปัสสาวะหาสารเสพติด",
    "reportedBy": "Rama2_Club",
    "severity": "high"
  },
  {
    "id": "cp-106",
    "title": "ด่านตรวจวัดแอลกอฮอล์ ถ.เกษตร-นวมินทร์",
    "type": "alcohol",
    "typeLabel": "ตรวจวัดแอลกอฮอล์",
    "locationName": "ตอม่อที่ 185 ถ.ประเสริฐมนูกิจ",
    "province": "กรุงเทพมหานคร",
    "district": "ลาดพร้าว",
    "lat": 13.8291,
    "lng": 100.6120,
    "direction": "มุ่งหน้าแยกลาดปลาเค้า",
    "status": "active",
    "verifiedCount": 73,
    "clearedCount": 5,
    "reportedAt": "2026-09-28T10:30:00+07:00",
    "description": "ตั้งด่านใหญ่ มีกล้องบันทึกภาพ ตรวจเป่าแอลกอฮอล์ 100%",
    "reportedBy": "NightDrive_TH",
    "severity": "high"
  },
  {
    "id": "cp-107",
    "title": "ด่านตรวจจราจร ถ.พหลโยธิน สะพานใหม่",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "หน้าตลาดยิ่งเจริญ สะพานใหม่",
    "province": "กรุงเทพมหานคร",
    "district": "บางเขน",
    "lat": 13.8967,
    "lng": 100.6062,
    "direction": "ขาออก (มุ่งหน้าดอนเมือง)",
    "status": "cleared",
    "verifiedCount": 15,
    "clearedCount": 38,
    "reportedAt": "2026-09-28T07:30:00+07:00",
    "description": "ช่วงเช้าตั้งด่านตรวจจักรยานยนต์ ขณะนี้เจ้าหน้าที่เคลียร์ด่านและยกเลิกแล้ว",
    "reportedBy": "Bangkhen_Live",
    "severity": "low"
  },
  {
    "id": "cp-108",
    "title": "ด่านชั่งน้ำหนักยานพาหนะ บรมราชชนนี",
    "type": "weigh",
    "typeLabel": "ด่านชั่งน้ำหนักรถบรรทุก",
    "locationName": "ถ.บรมราชชนนี สาย 4 ขาออก",
    "province": "นครปฐม",
    "district": "สามพราน",
    "lat": 13.7885,
    "lng": 100.3241,
    "direction": "ขาออก มุ่งหน้านครชัยศรี",
    "status": "active",
    "verifiedCount": 19,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T09:15:00+07:00",
    "description": "กรมทางหลวงตั้งจุดสกัดชั่งน้ำหนักเคลื่อนที่สำหรับรถบรรทุก 10 ล้อขึ้นไป",
    "reportedBy": "Logistics_TH",
    "severity": "medium"
  },
  {
    "id": "cp-109",
    "title": "จุดตรวจบูรณาการ ถ.ซุปเปอร์ไฮเวย์ เชียงใหม่",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ด่านดอนจั่น ถ.ซุปเปอร์ไฮเวย์ เชียงใหม่-ลำปาง",
    "province": "เชียงใหม่",
    "district": "เมืองเชียงใหม่",
    "lat": 18.7735,
    "lng": 99.0354,
    "direction": "ขาเข้าเมืองเชียงใหม่",
    "status": "active",
    "verifiedCount": 61,
    "clearedCount": 2,
    "reportedAt": "2026-09-28T10:00:00+07:00",
    "description": "ด่านตรวจหลักเข้าเมืองเชียงใหม่ ตรวจเอกสาร ตรวจค้นสิ่งผิดกฎหมาย",
    "reportedBy": "CM_TrafficNews",
    "severity": "high"
  },
  {
    "id": "cp-110",
    "title": "ด่านตรวจวัดแอลกอฮอล์ ถ.สุขุมวิท พัทยา",
    "type": "alcohol",
    "typeLabel": "ตรวจวัดแอลกอฮอล์",
    "locationName": "แยกพัทยาใต้ มุ่งหน้าจอมเทียน",
    "province": "ชลบุรี",
    "district": "บางละมุง",
    "lat": 12.9150,
    "lng": 100.8920,
    "direction": "ขาออก พัทยาใต้",
    "status": "active",
    "verifiedCount": 49,
    "clearedCount": 3,
    "reportedAt": "2026-09-28T10:10:00+07:00",
    "description": "สภ.เมืองพัทยา ตรวจวัดแอลกอฮอล์นักท่องเที่ยวและผู้ขับขี่",
    "reportedBy": "Pattaya_CheckDan",
    "severity": "high"
  },
  {
    "id": "cp-111",
    "title": "ด่านตรวจสบปราบ ถ.พหลโยธิน ลำปาง",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ถ.พหลโยธิน กม.650 อ.สบปราบ",
    "province": "ลำปาง",
    "district": "สบปราบ",
    "lat": 17.8921,
    "lng": 99.2144,
    "direction": "ขาขึ้นเชียงใหม่ (สายเหนือ)",
    "status": "active",
    "verifiedCount": 88,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T08:30:00+07:00",
    "description": "ด่านตรวจความมั่นคงและยาเสพติดหลักสายเหนือ มีการเรียกตรวจค้นรถยนต์ทุกประเภท",
    "reportedBy": "NorthernHighway",
    "severity": "high"
  },
  {
    "id": "cp-112",
    "title": "ด่านตรวจสะพานเดชาณุวงศ์ ถ.พหลโยธิน",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "เชิงสะพานเดชาณุวงศ์ ขาออก",
    "province": "นครสวรรค์",
    "district": "เมืองนครสวรรค์",
    "lat": 15.6912,
    "lng": 100.1245,
    "direction": "ขาขึ้นเหนือ มุ่งหน้าพิษณุโลก/กำแพงเพชร",
    "status": "active",
    "verifiedCount": 42,
    "clearedCount": 3,
    "reportedAt": "2026-09-28T09:40:00+07:00",
    "description": "ตำรวจจราจรนครสวรรค์ ตรวจจับความเร็ว ใบขับขี่ รถบรรทุกวิ่งขวา",
    "reportedBy": "Paknampho_News",
    "severity": "medium"
  },
  {
    "id": "cp-113",
    "title": "ด่านตรวจยานพาหนะชุมพร (ประตูสู่ภาคใต้)",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ถ.เพชรเกษม (ทล.4) ต.หงษ์เจริญ อ.ท่าแซะ",
    "province": "ชุมพร",
    "district": "ท่าแซะ",
    "lat": 10.6841,
    "lng": 99.1523,
    "direction": "ขาล่องใต้ มุ่งหน้าสุราษฎร์ธานี",
    "status": "active",
    "verifiedCount": 115,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T07:15:00+07:00",
    "description": "ด่านเอกซเรย์ยาเสพติดและสิ่งผิดกฎหมายหลักประตูสู่ 14 จังหวัดภาคใต้",
    "reportedBy": "South_Gateway",
    "severity": "high"
  },
  {
    "id": "cp-114",
    "title": "ด่านตรวจภูเก็ต (ท่าฉัตรไชย)",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "สะพานท้าวเทพกระษัตรี-ท้าวศรีสุนทร ด่านตรวจท่าฉัตรไชย",
    "province": "ภูเก็ต",
    "district": "ถลาง",
    "lat": 8.2014,
    "lng": 98.2982,
    "direction": "ขาเข้าเกาะภูเก็ต",
    "status": "active",
    "verifiedCount": 140,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T08:00:00+07:00",
    "description": "ด่านตรวจคัดกรองยานพาหนะ บุคคล และสิ่งของผิดกฎหมาย เข้าเกาะภูเก็ต 24 ชม.",
    "reportedBy": "Phuket_Portal",
    "severity": "high"
  },
  {
    "id": "cp-115",
    "title": "กล้องจับความเร็ว มอเตอร์เวย์ M7 พานทอง",
    "type": "speed",
    "typeLabel": "กล้องจับความเร็ว",
    "locationName": "มอเตอร์เวย์ สาย 7 กม.67 ด่านพานทอง",
    "province": "ชลบุรี",
    "district": "พานทอง",
    "lat": 13.4320,
    "lng": 101.0782,
    "direction": "ทั้งขาเข้าและขาออก (จำกัด 120 กม./ชม.)",
    "status": "active",
    "verifiedCount": 98,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T06:00:00+07:00",
    "description": "ระบบกล้องตรวจจับความเร็วอัตโนมัติเชื่อมต่อระบบออกใบสั่งอิเล็กทรอนิกส์",
    "reportedBy": "Motorway_HighwayPolice",
    "severity": "low"
  },
  {
    "id": "cp-116",
    "title": "ด่านตรวจทางหลวงสีคิ้ว ถ.มิตรภาพ",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ถ.มิตรภาพ กม.102 แยกสีคิ้ว",
    "province": "นครราชสีมา",
    "district": "สีคิ้ว",
    "lat": 14.8912,
    "lng": 101.7180,
    "direction": "ขาเข้าโคราช มุ่งหน้าขอนแก่น/อีสาน",
    "status": "active",
    "verifiedCount": 54,
    "clearedCount": 2,
    "reportedAt": "2026-09-28T09:30:00+07:00",
    "description": "ตำรวจทางหลวงสีคิ้ว ตรวจจับความเร็ว เลนขวา และตรวจสภาพรถ",
    "reportedBy": "Korat_Mitrapap",
    "severity": "medium"
  },
  {
    "id": "cp-117",
    "title": "ด่านตรวจร่วมท่าพระ ถ.มิตรภาพ ขอนแก่น",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ถ.มิตรภาพ ต.ท่าพระ หน้าศูนย์วิจัยพืช",
    "province": "ขอนแก่น",
    "district": "เมืองขอนแก่น",
    "lat": 16.3341,
    "lng": 102.8021,
    "direction": "ขาเข้าเมืองขอนแก่น",
    "status": "active",
    "verifiedCount": 38,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T10:10:00+07:00",
    "description": "ตรวจวินัยจราจร สวมหมวกนิรภัย คาดเข็มขัดนิรภัย ใบขับขี่",
    "reportedBy": "KK_TrafficReport",
    "severity": "medium"
  },
  {
    "id": "cp-118",
    "title": "ด่านตรวจสายเอเชีย บางปะอิน (AH2)",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ทางหลวงหมายเลข 32 (สายเอเชีย) กม.4 ต่างระดับบางปะอิน",
    "province": "พระนครศรีอยุธยา",
    "district": "บางปะอิน",
    "lat": 14.2468,
    "lng": 100.5971,
    "direction": "ขาออก มุ่งหน้าอยุธยา/อ่างทอง",
    "status": "active",
    "verifiedCount": 67,
    "clearedCount": 4,
    "reportedAt": "2026-09-28T10:05:00+07:00",
    "description": "ตำรวจทางหลวงอยุธยา โบกรถตรวจสอบความเร็วและรถบรรทุกน้ำหนักเกิน",
    "reportedBy": "AsiaHwy_Driver",
    "severity": "medium"
  },
  {
    "id": "cp-119",
    "title": "ด่านตรวจชั่งน้ำหนักและกวดขัน ถ.เพชรเกษม ท่ายาง",
    "type": "weigh",
    "typeLabel": "ด่านชั่งน้ำหนักรถบรรทุก",
    "locationName": "ถ.เพชรเกษม กม.168 อ.ท่ายาง",
    "province": "เพชรบุรี",
    "district": "ท่ายาง",
    "lat": 12.9642,
    "lng": 99.9870,
    "direction": "ขาล่องใต้ มุ่งหน้าชะอำ/หัวหิน",
    "status": "active",
    "verifiedCount": 31,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T08:50:00+07:00",
    "description": "จุดตรวจสอบน้ำหนักรถบรรทุกร่วมกับกวดขันวินัยจราจร",
    "reportedBy": "Phetchaburi_Logistics",
    "severity": "medium"
  },
  {
    "id": "cp-120",
    "title": "ด่านตรวจความมั่นคง สี่แยกอินโดจีน พิษณุโลก",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "วงเวียนสี่แยกอินโดจีน เลี่ยงเมืองพิษณุโลก",
    "province": "พิษณุโลก",
    "district": "เมืองพิษณุโลก",
    "lat": 16.8285,
    "lng": 100.3210,
    "direction": "เส้นทางเชื่อมเหนือ-อีสาน (ทล.12)",
    "status": "active",
    "verifiedCount": 44,
    "clearedCount": 2,
    "reportedAt": "2026-09-28T09:15:00+07:00",
    "description": "จุดตรวจบูรณาการตำรวจภูธรเมืองพิษณุโลก สกัดกั้นสิ่งผิดกฎหมาย",
    "reportedBy": "Indochina_Crossroad",
    "severity": "high"
  },
  {
    "id": "cp-121",
    "title": "ด่านตรวจเกาะยอ สี่แยกเกาะยอ สงขลา",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ถ.ลพบุรีราเมศวร์ เชื่อมสะพานติณสูลานนท์",
    "province": "สงขลา",
    "district": "เมืองสงขลา",
    "lat": 7.1512,
    "lng": 100.5702,
    "direction": "ขาเข้าเมืองสงขลา",
    "status": "active",
    "verifiedCount": 52,
    "clearedCount": 3,
    "reportedAt": "2026-09-28T09:45:00+07:00",
    "description": "ตรวจวินัยจราจร หมวกกันน็อก และความมั่นคงเข้าพื้นที่อำเภอเมือง",
    "reportedBy": "Songkhla_Today",
    "severity": "medium"
  },
  {
    "id": "cp-122",
    "title": "ด่านตรวจวัดแอลกอฮอล์ ถ.กาญจนวานิชย์ หาดใหญ่",
    "type": "alcohol",
    "typeLabel": "ตรวจวัดแอลกอฮอล์",
    "locationName": "หน้า ม.สงขลานครินทร์ (มอ. หาดใหญ่)",
    "province": "สงขลา",
    "district": "หาดใหญ่",
    "lat": 7.0084,
    "lng": 100.4988,
    "direction": "ขาเข้าเมืองหาดใหญ่",
    "status": "active",
    "verifiedCount": 63,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T10:15:00+07:00",
    "description": "สภ.คอหงส์ ตั้งด่านตรวจวัดแอลกอฮอล์ยามค่ำคืนและกวดขันรถแต่งซิ่ง",
    "reportedBy": "Hatyai_NightCheck",
    "severity": "high"
  },
  {
    "id": "cp-123",
    "title": "ด่านตรวจทางหลวงสระบุรี ถ.มิตรภาพ แก่งคอย",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ถ.มิตรภาพ กม.15 อ.แก่งคอย",
    "province": "สระบุรี",
    "district": "แก่งคอย",
    "lat": 14.5821,
    "lng": 101.0024,
    "direction": "ขาขึ้นอีสาน มุ่งหน้ามวกเหล็ก/ปากช่อง",
    "status": "active",
    "verifiedCount": 77,
    "clearedCount": 5,
    "reportedAt": "2026-09-28T08:40:00+07:00",
    "description": "ด่านตรวจความเร็วและวิ่งแช่ขวา ช่วงขึ้นเขามวกเหล็ก",
    "reportedBy": "Saraburi_Expressway",
    "severity": "medium"
  },
  {
    "id": "cp-124",
    "title": "ด่านตรวจส้มโอพญาเม็งราย ถ.เชียงราย-เทิง",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ทางหลวง 1020 อ.เทิง",
    "province": "เชียงราย",
    "district": "เทิง",
    "lat": 19.6841,
    "lng": 100.1852,
    "direction": "ขาเข้าเมืองเชียงราย",
    "status": "active",
    "verifiedCount": 33,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T07:50:00+07:00",
    "description": "ตรวจค้นสิ่งของลักลอบนำเข้า ยาเสพติด และแรงงานต่างด้าว",
    "reportedBy": "ChiangRai_BorderGuard",
    "severity": "high"
  },
  {
    "id": "cp-125",
    "title": "ด่านตรวจทางหลวงเอเชีย 41 ท่ากูบ สุราษฎร์ธานี",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "สี่แยกท่ากูบ ทางหลวง 41 ตัดทางหลวง 401",
    "province": "สุราษฎร์ธานี",
    "district": "เมืองสุราษฎร์ธานี",
    "lat": 9.1172,
    "lng": 99.3082,
    "direction": "ขาล่องใต้ มุ่งหน้าทุ่งสง/หาดใหญ่",
    "status": "active",
    "verifiedCount": 58,
    "clearedCount": 2,
    "reportedAt": "2026-09-28T09:25:00+07:00",
    "description": "ตรวจกวดขันวินัยจราจร เลนขวา และตรวจความเร็วบนทางหลวงสายใต้",
    "reportedBy": "Surat_HighwayWatch",
    "severity": "medium"
  },
  {
    "id": "cp-126",
    "title": "ด่านตรวจถ.แสงชูโต ท่าม่วง กาญจนบุรี",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ถ.แสงชูโตสายเก่า หน้าวัดถ้ำเสือ อ.ท่าม่วง",
    "province": "กาญจนบุรี",
    "district": "ท่าม่วง",
    "lat": 13.9582,
    "lng": 99.6381,
    "direction": "ขาเข้าเมืองกาญจนบุรี",
    "status": "active",
    "verifiedCount": 29,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T10:00:00+07:00",
    "description": "ตรวจหมวกกันน็อก ใบขับขี่ รถจักรยานยนต์ดัดแปลงสภาพ",
    "reportedBy": "Kanchanaburi_Rider",
    "severity": "low"
  },
  {
    "id": "cp-127",
    "title": "จุดตรวจโนนสูง ถ.มิตรภาพ อุดรธานี",
    "type": "traffic",
    "typeLabel": "กวดขันวินัยจราจร",
    "locationName": "ถ.มิตรภาพ กม.438 แยกโนนสูง",
    "province": "อุดรธานี",
    "district": "เมืองอุดรธานี",
    "lat": 17.2915,
    "lng": 102.8310,
    "direction": "ขาเข้าเมืองอุดรธานี จากขอนแก่น",
    "status": "active",
    "verifiedCount": 41,
    "clearedCount": 1,
    "reportedAt": "2026-09-28T09:10:00+07:00",
    "description": "ตรวจจับความเร็วเกิน 90 กม./ชม. และกวดขันรถไม่ชิดซ้าย",
    "reportedBy": "Udon_TrafficCheck",
    "severity": "medium"
  },
  {
    "id": "cp-128",
    "title": "ด่านตรวจวารินชำราบ อุบลราชธานี",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ถ.สถลมาร์ค หน้าค่ายสรรพสิทธิประสงค์",
    "province": "อุบลราชธานี",
    "district": "วารินชำราบ",
    "lat": 15.1923,
    "lng": 104.8621,
    "direction": "ขาเข้าเมืองอุบลราชธานี",
    "status": "active",
    "verifiedCount": 35,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T08:20:00+07:00",
    "description": "จุดตรวจร่วมสารวัตรทหารและตำรวจภูธร ดูแลความสงบเรียบร้อย",
    "reportedBy": "Ubon_Ratchathani_News",
    "severity": "high"
  },
  {
    "id": "cp-129",
    "title": "ด่านตรวจแม่สอด ถ.สายเอเชีย 1 (AH1) ตาก",
    "type": "security",
    "typeLabel": "จุดตรวจร่วมความมั่นคง",
    "locationName": "ด่านตรวจห้วยหินฝน ถ.สายตาก-แม่สอด",
    "province": "ตาก",
    "district": "แม่สอด",
    "lat": 16.7142,
    "lng": 98.6214,
    "direction": "ทั้งสองฝั่ง (ชายแดนไทย-เมียนมา)",
    "status": "active",
    "verifiedCount": 89,
    "clearedCount": 0,
    "reportedAt": "2026-09-28T07:00:00+07:00",
    "description": "ด่านความมั่นคงตรวจคนเข้าเมือง สิ่งของผิดกฎหมาย และสิ่งเทียมอาวุธ 24 ชม.",
    "reportedBy": "Tak_BorderWatch",
    "severity": "high"
  },
  {
    "id": "cp-130",
    "title": "ด่านตรวจสุขุมวิท มาบตาพุด ระยอง",
    "type": "smoke",
    "typeLabel": "ตรวจควันดำ/มลพิษ",
    "locationName": "ถ.สุขุมวิท หน้าศูนย์ราชการจังหวัดระยอง",
    "province": "ระยอง",
    "district": "เมืองระยอง",
    "lat": 12.6951,
    "lng": 101.2184,
    "direction": "ขาเข้าเมืองระยอง",
    "status": "active",
    "verifiedCount": 26,
    "clearedCount": 2,
    "reportedAt": "2026-09-28T10:00:00+07:00",
    "description": "ตรวจวัดมลพิษและควันดำยานพาหนะขนส่งโรงงานอุตสาหกรรม",
    "reportedBy": "Rayong_PollutionControl",
    "severity": "medium"
  }
];
